#!/bin/bash
#
# Reload user's launch agents.
#
# Usage: reloadd [PATTERN]
#   PATTERN	agents that match PATTERN are reloaded (defaults to com.$USER)

IDPAT="${1:-com.$USER}"
AGENTSPATH="$HOME/Library/LaunchAgents"

launchctl list | awk '{print $3}' | grep -E "$IDPAT" | while read id; do
	PLISTPATH="$AGENTSPATH/$id.plist"
	echo "Unloading: $PLISTPATH"
	2>&1 launchctl unload "$PLISTPATH" |
		grep -q failed &&
		launchctl bootout "gui/$UID/$id"
done

ls "$AGENTSPATH" | grep "$IDPAT" | while read plist; do
	echo "Loading: $AGENTSPATH/$plist"
	launchctl load "$AGENTSPATH/$plist"
done

exit 0
