#line 1 "src/tab.yy.c"

#line 3 "src/tab.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[332] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   24,   22,   22,    6,   22,   22,   22,   22,
       22,   22,   22,   22,   22,    6,   22,   22,   22,   22,
       22,    6,   22,   22,   22,   22,    6,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,    6,
       22,   22,    0,    6,    0,    0,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       10,    0,    0,    6,    0,    0,    0,    0,    1,    0,
        0,    9,    0,    7,    0,    0,   11,    0,    6,    0,

        0,    0,    0,    1,    0,    8,    0,    0,   21,    0,
        0,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    1,    0,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,    0,
        6,    0,    0,    0,    0,    1,    0,    0,    0,    3,
        0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    1,    0,    0,   15,    0,    0,
        0,    1,    0,    0,    0,    0,    0,    0,   16,    0,
        0,    0,   15,    0,   17,    0,    0,    0,   15,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    4,    0,    0,    0,    0,    0,   12,    0,
       18,    0,    0,    0,   15,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    5,
        0,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    0,    0,    0,    2,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    5,    1,    5,    6,    7,    5,    8,    8,    9,
        8,    8,    8,    8,    8,    8,    8,    1,    1,   10,
       11,   12,    1,   13,    7,    7,    7,    7,    7,    7,
        7,    7,   14,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       15,   16,   17,    1,    7,    1,   18,   19,    7,   20,

       21,    7,   22,   23,   24,    7,   25,   26,   27,   28,
       29,    7,    7,   30,    7,   31,   32,   33,   34,    7,
       35,    7,   36,    1,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    2,    3,    1,    2,    2,    1,    2,    2,    1,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[369] =
    {   0,
        0,    0,    0,    3,    0,   17,    0,   20,    0,   56,
        0,   23,   77, 1192,   28, 1192,   32,   26,   70,   36,
       84,   94,  129,   38,   99, 1192,   40,   47,   95,   42,
      105, 1192,   49,   85,  116,  165, 1192,  145,  179,  189,
      199,  147,   97,  149,  210,  161,  245,  120,  151, 1192,
      123,  212,  134, 1192,  159,  214,  217, 1192,   44,   80,
      220,    0,  223,  281,    0,  296,  240,  256,  229,  102,
      225,  252,  262,  264,  266,  269,  284,   31,  236,  300,
     1192,  307,  315, 1192,  312,  318,  322,  324, 1192,  327,
      333, 1192,  339, 1192,  276,  342, 1192,  344, 1192,  350,

      354,  356,  358, 1192,  360, 1192,  362,  364, 1192,  366,
        0, 1192,  368,   24,  104,    0,  374,  380,  384,    0,
      386,  414,  388,  390, 1192,  400,  450, 1192,  187,  402,
      409,  425,  404,  406,  430,  432,  419,  435,  446,  463,
      465,  467,  469,  480,  482,    0,  437,  442, 1192,  493,
     1192,  484,  500,  502,  505, 1192,  508,  513,  515, 1192,
      517,  519, 1192,  521,  522,  523,  526,  529,  533,  534,
      530,  537,  554,  557, 1192,  540,  560, 1192,  564,  566,
      568, 1192,  572,  580,  582,  584,  586,  588, 1192,  594,
      598,  600, 1192,  602, 1192,  604,  606,  608, 1192,  612,

      614,  616,  619,  626,  630,  632,  644,  648,  654,  642,
      658,  661,  665,  664,  263,  670,  666,  674,  677,  676,
      678,  680, 1192,  690,  695,  700,  707,  715, 1192,  725,
     1192,  727,  729,  731, 1192,  735,  737,  739,  741,  743,
      745,  747,  750,  757,  761,  771,  778,  781,  783, 1192,
      763, 1192,  793,  693,  765,  688,  795,  768,  801,  802,
      803,  829,  807,  813,  815,  837,  839,  842,  844,  849,
      859,  866,  871,  878,  877,  498,  879,  887,  889,  825,
      891,  894,  928,  909,  905,  916,  921,  936,  938,  942,
      952,  954,  962,  895,  847,  852,  911,  986,  971,  973,

      996,  998, 1000, 1008,  948,  818, 1018,  820,  950, 1032,
     1020, 1025, 1040, 1044,  822, 1192, 1055,  892,  976, 1192,
     1065, 1073,   11,  983, 1002, 1077, 1022, 1042, 1192, 1045,
     1192, 1086, 1089, 1092, 1095, 1098, 1101, 1104, 1107, 1109,
     1112, 1114, 1117, 1120, 1123, 1126, 1129, 1132, 1135, 1138,
     1141, 1144, 1147, 1150, 1153,    8, 1156, 1159, 1162, 1165,
     1168, 1171, 1174, 1177, 1180, 1183, 1186, 1188
    } ;

static const flex_int16_t yy_def[369] =
    {   0,
      332,  332,  332,  333,  332,  334,  332,  335,  332,  336,
      332,  337,  331,  331,  331,  331,  338,  339,  339,  340,
      339,  339,  341,  342,  342,  331,  343,  342,  342,  344,
      344,  331,  345,  344,  346,  346,  331,  347,  346,  346,
      346,  348,  349,  350,  346,  346,  351,  352,  352,  331,
      353,  352,  331,  331,  338,  338,  338,  331,  339,  331,
      354,   19,  340,   19,   22,  341,  340,  338,  355,  356,
      339,  339,  339,  339,  339,  339,  339,   66,  342,  342,
      331,  342,  342,  331,  343,  342,  343,  343,  331,  343,
      342,  331,  342,  331,  344,  344,  331,  344,  331,  345,

      344,  345,  345,  331,  344,  331,  346,  349,  331,  357,
       36,  331,  347,   41,   41,   41,  348,  349,  350,   45,
      346,  351,  347,  358,  331,  359,  349,  331,   41,  360,
      348,  361,  362,  349,  350,  363,  364,  346,  346,  346,
      346,  346,  346,  346,  346,  122,  352,  352,  331,  352,
      331,  353,  352,  353,  353,  331,  352,  354,  354,  331,
      355,  355,  331,  331,  339,  339,  339,  339,  339,  339,
      339,  339,  339,  343,  331,  357,  357,  331,  358,  359,
      359,  331,  349,   41,  360,  365,  366,  361,  331,  361,
      362,  362,  331,  363,  331,  363,  364,  364,  331,  346,

      346,  346,  346,  346,  346,  346,  346,  346,  346,  352,
      354,  355,  331,  339,  339,  339,  339,  339,  339,  339,
      339,  331,  331,  357,  358,  359,  349,  349,  331,  365,
      331,  365,  366,  366,  331,  361,  362,  363,  364,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  349,  331,
      352,  331,  331,  339,  339,  339,  339,  339,  339,  339,
      339,  349,  365,  366,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  331,  339,  339,  339,  339,  339,  339,
      339,  339,  349,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  331,  339,  367,  339,  339,  349,  346,  349,

      346,  346,  346,  331,  339,  367,  367,  368,  339,  349,
      346,  346,  346,  331,  367,  331,  367,  368,  368,  331,
      349,  349,  367,  368,  349,  349,  367,  349,  331,  367,
        0,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331
    } ;

static const flex_int16_t yy_nxt[1230] =
    {   0,
      331,   15,   16,   17,   19,   16,   20,   21,   21,  164,
       21,   21,  327,   14,  331,   22,  209,   23,   25,   26,
       27,   31,   32,   33,   49,   50,   51,   60,   52,   53,
       54,   55,   28,   57,   58,  107,   61,   68,   58,   80,
       81,   88,   89,   96,   97,   60,   69,  173,   91,   92,
      103,  104,   29,   82,   61,   90,   34,   36,   37,   38,
       39,   40,   82,   39,   41,   42,   43,   44,   45,   46,
       47,   62,   54,   63,   64,   64,  331,   64,   64,  331,
      331,   60,   65,  331,   66,   70,  105,  106,   64,   64,
       61,   64,   64,  331,   61,   60,   93,   94,  134,  109,

       83,   84,   85,   70,   61,  331,   98,   99,  100,  129,
       82,   71,   61,   72,   82,  107,   73,  108,  109,  331,
       74,  148,  149,   75,  155,  156,  110,   76,   77,   59,
       60,  331,   59,   59,   86,   53,   54,   55,   59,   61,
       59,  101,  331,   59,   59,   59,  124,  125,  132,  109,
      136,  109,  150,  151,  152,  126,  153,  133,  331,  137,
       57,   58,  108,  109,   59,   59,  111,  112,  113,  114,
      115,  110,  114,  116,  117,  118,  119,  120,  121,  122,
      127,  128,  331,  114,  114,  331,  114,  114,  145,  110,
      127,  128,  184,  114,  129,  331,  114,  114,  107,  110,

      127,  128,  331,  114,  114,  331,  114,  114,  331,  110,
      130,  108,  109,  148,  149,   57,   58,  157,   57,   58,
      110,  159,  160,  331,   68,   58,   60,  138,  331,  139,
      162,  163,  140,   69,  331,   61,  141,   80,   81,  142,
      331,   68,   58,  143,  144,  107,  108,  109,  107,  107,
       69,   82,  165,   60,  107,  110,  107,   68,   58,  107,
      107,  107,   61,   60,   60,   60,   69,   60,  331,  166,
       60,  331,   61,   61,   61,  331,   61,   96,   97,   61,
      107,  107,   70,  331,   59,   60,  170,  168,  255,  171,
      167,   61,  169,   59,   61,   59,   59,   60,  331,   59,

       59,   80,   81,  331,  172,   59,   61,   59,   91,   92,
       59,   59,   59,   88,   89,   82,   83,   84,   85,   93,
       94,  331,   82,   88,   89,   88,   89,   90,  174,  175,
       82,   59,   59,   82,   91,   92,  331,   90,  331,   90,
       93,   94,   90,   96,   97,   98,   99,  100,   82,  331,
       86,  103,  104,  331,   82,  105,  106,  103,  104,  103,
      104,  105,  106,  108,  109,  108,  109,  177,  178,  124,
      125,  331,  110,  331,  110,  132,  109,  331,  126,  331,
      101,  134,  109,  331,  133,  136,  109,  108,  109,  124,
      125,  124,  125,  331,  137,  331,  110,  331,  126,  331,

      126,  181,  182,  186,  109,  192,  193,  134,  109,  331,
      188,  189,  187,  145,  107,  108,  109,  107,  107,  133,
      198,  199,  331,  107,  110,  107,  188,  189,  107,  107,
      107,  194,  195,  194,  195,  133,  108,  109,  148,  149,
      137,  331,  137,  148,  149,  110,  331,  108,  109,  107,
      107,  127,  128,  331,  183,  183,  110,  183,  183,  331,
      110,  331,  200,  201,  108,  109,  108,  109,  108,  109,
      108,  109,  331,  110,  331,  110,  331,  110,  331,  110,
      331,  108,  109,  108,  109,  155,  156,  205,  203,  206,
      110,  202,  110,  204,  150,  151,  152,  331,  153,  295,

      207,  148,  149,  155,  156,  157,  155,  156,   61,  148,
      149,  331,  208,  210,  211,  160,  159,  160,  212,  163,
      162,  163,  213,   60,   60,  164,  164,   60,  164,  164,
       60,   60,   61,   61,   60,   60,   61,  331,   60,   61,
       61,  224,  178,   61,   61,  331,  215,   61,  217,  214,
      220,  331,  219,  331,  221,  222,  223,  216,  174,  175,
      218,  177,  178,  331,   61,  225,  125,  226,  182,  181,
      182,  331,   90,  227,  128,  331,  183,  183,  331,  183,
      183,  228,  229,  230,  231,  230,  231,  234,  235,  188,
      189,  107,  187,  331,  187,  236,  189,  331,  133,  237,

      193,  192,  193,  194,  195,  238,  195,  239,  199,  198,
      199,  331,  137,  108,  109,  108,  109,  108,  109,  331,
      108,  109,  110,  331,  110,  331,  110,  108,  109,  110,
      331,  108,  109,  108,  109,  331,  110,  241,  243,  240,
      110,  331,  110,  251,  252,  108,  109,  242,  245,  108,
      109,  331,  246,  244,  110,  249,  250,  331,  110,  211,
      160,  247,  212,  163,  110,   60,  213,   60,  248,  253,
      253,   60,  253,  253,   61,   60,   61,   60,   60,   60,
       61,  222,  223,  331,   61,  331,   61,   61,   61,   60,
       61,  224,  178,  257,   60,  254,  225,  125,   61,  256,

      260,  226,  182,   61,  258,  259,  331,  261,  227,  128,
      275,  262,  262,  277,  262,  262,  228,  229,  331,  183,
      183,  331,  183,  183,  331,  110,  230,  231,  263,  231,
      264,  235,  234,  235,  331,  187,  236,  189,  237,  193,
      238,  195,  239,  199,  108,  109,  108,  109,  108,  109,
      331,  108,  109,  110,  331,  110,  331,  110,  108,  109,
      110,  331,  108,  109,  251,  252,   60,  110,  331,   60,
      266,  110,  108,  109,  265,   61,  267,  268,   61,  108,
      109,  110,  108,  109,  249,  250,  331,  269,  110,  270,
      279,  110,  331,  110,  274,  271,   60,  253,  253,  276,

      253,  253,   60,   60,   60,   61,  331,  272,  263,  231,
      273,   61,   61,   61,  264,  235,  108,  109,  278,  315,
      316,  319,  320,  315,  316,  110,   60,  281,  282,  280,
      283,  128,  284,  262,  262,   61,  262,  262,  108,  109,
      108,  109,  331,  108,  109,  108,  109,  110,  307,  110,
      108,  109,  110,   60,  110,  276,  331,  308,  331,  110,
      108,  109,   61,  331,  286,  287,  288,  108,  109,  110,
      331,  285,  108,  109,  309,  331,  110,  289,   60,  274,
       60,  110,  293,  293,  290,  293,  293,   61,   60,   61,
       60,  291,   60,  324,  320,   60,   60,   61,  331,   61,

      331,   61,  294,  292,   61,   61,  300,  128,  296,  331,
      108,  109,   60,  276,  297,  110,  331,  108,  109,  110,
      305,   61,  108,  109,  331,  276,  110,  331,  276,  283,
      128,  110,  298,  298,  299,  298,  298,  108,  109,  108,
      109,  331,  301,  108,  109,  276,  110,  331,  110,   60,
      285,   60,  110,  108,  109,  108,  109,  331,   61,  331,
       61,  302,  110,  304,  110,  331,  293,  293,  285,  293,
      293,  303,  108,  109,  300,  128,  285,  319,  320,  331,
      276,  110,  276,  110,  324,  320,  285,  310,  128,  331,
      298,  298,  331,  298,  298,  331,  311,  108,  109,  108,

      109,  108,  109,  325,  128,  331,  110,  331,  110,  304,
      110,  331,  314,  314,  331,  314,  314,  331,  312,  317,
      316,  108,  109,  330,  316,  313,  108,  109,  308,  331,
      110,  331,  285,  310,  128,  110,  321,  321,  331,  321,
      321,  322,  109,  328,  329,  323,  330,  316,  314,  314,
      110,  314,  314,  331,  285,  285,  317,  316,  331,  331,
      331,  331,  331,  331,  331,  308,  325,  128,  331,  321,
      321,  331,  321,  321,  322,  109,  331,  331,  328,  329,
      326,  326,  331,  110,  326,  326,   14,   14,   14,   18,
       18,   18,   24,   24,   24,   30,   30,   30,   35,   35,

       35,   48,   48,   48,   56,   56,   56,   59,   59,   67,
       67,   67,   78,   78,   79,   79,   79,   87,   87,   87,
       95,   95,   95,  102,  102,  102,  107,  107,  107,  123,
      123,  123,  131,  131,  131,  118,  118,  118,  135,  135,
      135,  146,  146,  146,  147,  147,  147,  154,  154,  154,
      158,  158,  158,  161,  161,  161,  176,  176,  176,  179,
      179,  179,  180,  180,  180,  185,  185,  185,  190,  190,
      190,  191,  191,  191,  196,  196,  196,  197,  197,  197,
      232,  232,  232,  233,  233,  233,  306,  306,  318,  318,
      318,   13,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331
    } ;

static const flex_int16_t yy_chk[1230] =
    {   0,
        0,    2,    2,    2,    4,    4,    4,    4,    4,  356,
        4,    4,  323,    4,    0,    4,  146,    4,    6,    6,
        6,    8,    8,    8,   12,   12,   12,   18,   12,   15,
       15,   15,    6,   17,   17,  114,   18,   20,   20,   24,
       24,   27,   27,   30,   30,   59,   20,   78,   28,   28,
       33,   33,    6,   24,   59,   27,    8,   10,   10,   10,
       10,   10,   28,   10,   10,   10,   10,   10,   10,   10,
       10,   19,   19,   19,   19,   19,   13,   19,   19,    0,
       19,   60,   19,    0,   19,   21,   34,   34,   21,   21,
       60,   21,   21,    0,   21,   22,   29,   29,   43,   43,

       25,   25,   25,   70,   22,    0,   31,   31,   31,  115,
       29,   22,   70,   22,   25,  115,   22,   35,   35,    0,
       22,   48,   48,   22,   51,   51,   35,   22,   22,   23,
       23,    0,   23,   23,   25,   53,   53,   53,   23,   23,
       23,   31,    0,   23,   23,   23,   38,   38,   42,   42,
       44,   44,   49,   49,   49,   38,   49,   42,    0,   44,
       55,   55,   46,   46,   23,   23,   36,   36,   36,   36,
       36,   46,   36,   36,   36,   36,   36,   36,   36,   36,
       39,   39,    0,   39,   39,    0,   39,   39,   46,   39,
       40,   40,  129,   40,   40,    0,   40,   40,  129,   40,

       41,   41,    0,   41,   41,    0,   41,   41,    0,   41,
       41,   45,   45,   52,   52,   56,   56,   52,   57,   57,
       45,   61,   61,    0,   63,   63,   71,   45,    0,   45,
       69,   69,   45,   63,    0,   71,   45,   79,   79,   45,
        0,   67,   67,   45,   45,   47,   47,   47,   47,   47,
       67,   79,   71,   72,   47,   47,   47,   68,   68,   47,
       47,   47,   72,   73,  215,   74,   68,   75,    0,   72,
       76,    0,   73,  215,   74,    0,   75,   95,   95,   76,
       47,   47,   64,   64,   64,   77,   75,   74,  215,   76,
       73,   64,   74,   64,   77,   64,   66,   66,    0,   66,

       66,   80,   80,    0,   77,   66,   66,   66,   82,   82,
       66,   66,   66,   85,   85,   80,   83,   83,   83,   86,
       86,    0,   82,   87,   87,   88,   88,   85,   90,   90,
       83,   66,   66,   86,   91,   91,    0,   87,    0,   88,
       93,   93,   90,   96,   96,   98,   98,   98,   91,    0,
       83,  100,  100,    0,   93,  101,  101,  102,  102,  103,
      103,  105,  105,  107,  107,  108,  108,  110,  110,  113,
      113,    0,  107,    0,  108,  117,  117,    0,  113,    0,
       98,  118,  118,    0,  117,  119,  119,  121,  121,  123,
      123,  124,  124,    0,  119,    0,  121,    0,  123,    0,

      124,  126,  126,  130,  130,  133,  133,  134,  134,    0,
      131,  131,  130,  121,  122,  122,  122,  122,  122,  131,
      137,  137,    0,  122,  122,  122,  132,  132,  122,  122,
      122,  135,  135,  136,  136,  132,  138,  138,  147,  147,
      135,    0,  136,  148,  148,  138,    0,  139,  139,  122,
      122,  127,  127,    0,  127,  127,  139,  127,  127,    0,
      127,    0,  138,  139,  140,  140,  141,  141,  142,  142,
      143,  143,    0,  140,    0,  141,    0,  142,    0,  143,
        0,  144,  144,  145,  145,  152,  152,  142,  141,  143,
      144,  140,  145,  141,  150,  150,  150,    0,  150,  276,

      144,  153,  153,  154,  154,  153,  155,  155,  276,  157,
      157,    0,  145,  157,  158,  158,  159,  159,  161,  161,
      162,  162,  164,  165,  166,  164,  164,  167,  164,  164,
      168,  171,  165,  166,  169,  170,  167,    0,  172,  168,
      171,  176,  176,  169,  170,    0,  166,  172,  168,  165,
      171,    0,  170,    0,  172,  173,  173,  167,  174,  174,
      169,  177,  177,    0,  173,  179,  179,  180,  180,  181,
      181,    0,  174,  183,  183,    0,  183,  183,    0,  183,
      183,  184,  184,  185,  185,  186,  186,  187,  187,  188,
      188,  184,  185,    0,  186,  190,  190,    0,  188,  191,

      191,  192,  192,  194,  194,  196,  196,  197,  197,  198,
      198,    0,  194,  200,  200,  201,  201,  202,  202,    0,
      203,  203,  200,    0,  201,    0,  202,  204,  204,  203,
        0,  205,  205,  206,  206,    0,  204,  201,  203,  200,
      205,    0,  206,  210,  210,  207,  207,  202,  205,  208,
      208,    0,  206,  204,  207,  209,  209,    0,  208,  211,
      211,  207,  212,  212,  209,  214,  213,  217,  208,  213,
      213,  216,  213,  213,  214,  218,  217,  220,  219,  221,
      216,  222,  222,    0,  218,    0,  220,  219,  221,  256,
      222,  224,  224,  217,  254,  214,  225,  225,  256,  216,

      220,  226,  226,  254,  218,  219,    0,  221,  227,  227,
      254,  227,  227,  256,  227,  227,  228,  228,    0,  228,
      228,    0,  228,  228,    0,  228,  230,  230,  232,  232,
      233,  233,  234,  234,    0,  230,  236,  236,  237,  237,
      238,  238,  239,  239,  240,  240,  241,  241,  242,  242,
        0,  243,  243,  240,    0,  241,    0,  242,  244,  244,
      243,    0,  245,  245,  251,  251,  255,  244,    0,  258,
      241,  245,  246,  246,  240,  255,  242,  243,  258,  247,
      247,  246,  248,  248,  249,  249,    0,  244,  247,  245,
      258,  248,    0,  249,  253,  246,  257,  253,  253,  255,

      253,  253,  259,  260,  261,  257,    0,  247,  263,  263,
      248,  259,  260,  261,  264,  264,  265,  265,  257,  306,
      306,  308,  308,  315,  315,  265,  280,  260,  261,  259,
      262,  262,  265,  262,  262,  280,  262,  262,  266,  266,
      267,  267,    0,  268,  268,  269,  269,  266,  295,  267,
      270,  270,  268,  296,  269,  280,    0,  295,    0,  270,
      271,  271,  296,    0,  267,  268,  269,  272,  272,  271,
        0,  266,  273,  273,  296,    0,  272,  270,  275,  274,
      277,  273,  274,  274,  271,  274,  274,  275,  278,  277,
      279,  272,  281,  318,  318,  282,  294,  278,    0,  279,

        0,  281,  275,  273,  282,  294,  285,  285,  278,    0,
      284,  284,  297,  277,  279,  285,    0,  286,  286,  284,
      294,  297,  287,  287,    0,  281,  286,    0,  282,  283,
      283,  287,  283,  283,  284,  283,  283,  288,  288,  289,
      289,    0,  287,  290,  290,  297,  288,    0,  289,  305,
      286,  309,  290,  291,  291,  292,  292,    0,  305,    0,
      309,  288,  291,  293,  292,    0,  293,  293,  289,  293,
      293,  292,  299,  299,  300,  300,  290,  319,  319,    0,
      309,  299,  305,  300,  324,  324,  291,  298,  298,    0,
      298,  298,    0,  298,  298,    0,  299,  301,  301,  302,

      302,  303,  303,  325,  325,    0,  301,    0,  302,  304,
      303,    0,  304,  304,    0,  304,  304,    0,  301,  307,
      307,  311,  311,  327,  327,  303,  312,  312,  307,    0,
      311,    0,  302,  310,  310,  312,  310,  310,    0,  310,
      310,  313,  313,  328,  328,  314,  330,  330,  314,  314,
      313,  314,  314,    0,  311,  312,  317,  317,    0,    0,
        0,    0,    0,    0,    0,  317,  321,  321,    0,  321,
      321,    0,  321,  321,  322,  322,    0,    0,  326,  326,
      322,  322,    0,  322,  326,  326,  332,  332,  332,  333,
      333,  333,  334,  334,  334,  335,  335,  335,  336,  336,

      336,  337,  337,  337,  338,  338,  338,  339,  339,  340,
      340,  340,  341,  341,  342,  342,  342,  343,  343,  343,
      344,  344,  344,  345,  345,  345,  346,  346,  346,  347,
      347,  347,  348,  348,  348,  349,  349,  349,  350,  350,
      350,  351,  351,  351,  352,  352,  352,  353,  353,  353,
      354,  354,  354,  355,  355,  355,  357,  357,  357,  358,
      358,  358,  359,  359,  359,  360,  360,  360,  361,  361,
      361,  362,  362,  362,  363,  363,  363,  364,  364,  364,
      365,  365,  365,  366,  366,  366,  367,  367,  368,  368,
      368,  331,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[24] =
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    1, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/tab.l"
#line 2 "src/tab.l"
#include "launchtab.h"

static struct tab *curr_tab;
#line 856 "src/tab.yy.c"

#line 858 "src/tab.yy.c"

#define INITIAL 0
#define INISC 1
#define COMSC 2
#define MULSC 3
#define OPTSC 4
#define VERSC 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 37 "src/tab.l"


#line 1086 "src/tab.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 332 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1192 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 39 "src/tab.l"
{handle_comment(curr_tab);                    }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 40 "src/tab.l"
{handle_cronRule(curr_tab);                   }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 41 "src/tab.l"
{handle_globEnvar(curr_tab);                  }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 42 "src/tab.l"
{handle_id(curr_tab);             BEGIN COMSC;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 43 "src/tab.l"
{handle_id(curr_tab);             BEGIN COMSC;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 44 "src/tab.l"
{handle_emptyLine(curr_tab);                  }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 46 "src/tab.l"
{handle_commandStart(curr_tab);   BEGIN MULSC;}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 47 "src/tab.l"
{handle_commandEnd(curr_tab);     BEGIN OPTSC;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 48 "src/tab.l"
{handle_commandCont(curr_tab);                }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 49 "src/tab.l"
{handle_command(curr_tab);        BEGIN OPTSC;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 50 "src/tab.l"
{handle_commandMulti(curr_tab);               }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 52 "src/tab.l"
{handle_verbatimStart(curr_tab);  BEGIN VERSC;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 53 "src/tab.l"
{handle_interval(curr_tab);                   }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 54 "src/tab.l"
{handle_calendar(curr_tab);                   }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 55 "src/tab.l"
{handle_envar(curr_tab);                      }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 56 "src/tab.l"
{handle_stdin(curr_tab);                      }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 57 "src/tab.l"
{handle_stdout(curr_tab);                     }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 58 "src/tab.l"
{handle_stderr(curr_tab);                     }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 60 "src/tab.l"
{handle_verbatimEnd(curr_tab);    BEGIN OPTSC;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 61 "src/tab.l"
{handle_verbatimLine(curr_tab);               }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 62 "src/tab.l"
{handle_unknownOpt(curr_tab);                 }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 64 "src/tab.l"
{handle_invalid(curr_tab);      yyterminate();}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "src/tab.l"
ECHO;
	YY_BREAK
#line 1291 "src/tab.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INISC):
case YY_STATE_EOF(COMSC):
case YY_STATE_EOF(MULSC):
case YY_STATE_EOF(OPTSC):
case YY_STATE_EOF(VERSC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 332 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 332 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 331);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 66 "src/tab.l"


int yywrap(void)
{
	return 1;
}

void lex_tab(FILE *f, struct tab *t)
{
	yyin = f;
	yylineno = 1;
	curr_tab = t;
	BEGIN INISC;
	yylex();
}

