#line 1 "src/tab.yy.c"

#line 3 "src/tab.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 20
#define YY_END_OF_BUFFER 21
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[309] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       21,   19,   19,    6,   19,   19,   19,   19,   19,   19,
       19,   19,   19,    6,   19,   19,   19,   19,    6,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,    6,   19,   19,    0,    6,    0,    0,    0,    1,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    0,    6,    0,    0,    0,    1,
        0,    0,    7,    0,    0,   18,    0,    0,    6,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    1,    0,    0,   11,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   17,    0,    6,    0,    0,
        0,    0,    1,    0,    0,    0,    3,    0,    0,    1,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    1,    0,    0,   12,    0,    0,    0,    1,    0,
        0,    0,    0,    0,    0,   13,    0,    0,    0,   12,
        0,   14,    0,    0,    0,   12,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    4,

        0,    0,    0,    0,    0,    9,    0,   15,    0,    0,
        0,   12,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    5,    0,   16,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    0,    0,    0,    2,    0,    0,    0,

        0,    0,    0,    0,    0,   10,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    5,    1,    5,    6,    7,    5,    8,    8,    9,
        8,    8,    8,    8,    8,    8,    8,    1,    1,   10,
       11,   12,    1,   13,    7,    7,    7,    7,    7,    7,
        7,    7,   14,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       15,   16,   17,    1,    7,    1,   18,   19,    7,   20,

       21,    7,   22,   23,   24,    7,   25,   26,   27,   28,
       29,    7,    7,   30,    7,   31,   32,   33,   34,    7,
       35,    7,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[36] =
    {   0,
        1,    2,    3,    1,    2,    2,    1,    2,    2,    1,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[343] =
    {   0,
        0,    0,    0,    3,    0,   17,    0,   32,    0,   20,
       71, 1080,   25, 1080,   28,   37,   47,   61,   71,   81,
      116,   65,   82, 1080,   72,   87,   67,  132, 1080,   91,
      146,   55,   47,   94,   63,  111,  156,  159,  191,  104,
      162, 1080,  107,  169,  121, 1080,  127,  175,  178, 1080,
       89,  158,  182,    0,  186,  207,    0,  222,  202,  214,
      196,  171,  217,  229,  219,  233,  239,  240,  244,   40,
      250,  256, 1080,  261,  265, 1080,  268,  271,  273, 1080,
      276,  280, 1080,  283,  288, 1080,  212,    0, 1080,  295,
        0,   48,   20,  298,  300,  302,    0,  305,  333,  308,

      312, 1080,  315,  349, 1080,   19,  318,  328,  359,  322,
      324,  361,  363,  338,  365,  376,  378,  380,  394,  397,
      399,  410,    0,  344,  382, 1080,  420, 1080,  414,  425,
      427,  430, 1080,  432,  434,  437, 1080,  440,  442, 1080,
      444,  375,  445,  446,  452,  449,  456,  453,  468,  478,
      480, 1080,  459,  463, 1080,  482,  485,  488, 1080,  457,
      490,  492,  495,  497,  499, 1080,  502,  505,  509, 1080,
      511, 1080,  513,  515,  517, 1080,  521,  523,  525,  528,
      535,  539,  541,  553,  557,  563,  551,  567,  570,  574,
      573,  575,  579,  583,  585,  586,  587,  589,  611, 1080,

      590,  600,  604,  621,  615, 1080,  622, 1080,  618,  632,
      634, 1080,  636,  638,  640,  642,  644,  646,  648,  651,
      658,  662,  672,  679,  682,  684, 1080,  664, 1080,  694,
      690,  593,  696,  702,  704,  703,  708,  709,  734,  668,
      714,  727,  722,  744,  747,  749,  751,  762,  764,  766,
      776,  772,  597,  784,  666,  785,  789,  790,  791,  825,
      803,  801,  805,  821,  833,  807,  839,  843,  845,  856,
      811,  849,  864,  865,  899,  866,  868,  870,  880,  883,
      908,  886,  850,  887,  893,  901,  931,  916,  927,  920,
      939,  922, 1080,  950,  940,  947, 1080,  960,  968,   11,

      952,  954,  972,  957,  970, 1080,  980, 1080,  983,  986,
      989,  992,  995,  998, 1001, 1003, 1006, 1008, 1011, 1014,
     1017, 1020, 1023, 1026, 1029, 1032, 1035, 1038, 1041,    8,
     1044, 1047, 1050, 1053, 1056, 1059, 1062, 1065, 1068, 1071,
     1074, 1076
    } ;

static const flex_int16_t yy_def[343] =
    {   0,
      309,  309,  309,  310,  309,  311,  309,  312,  309,  313,
      308,  308,  308,  308,  314,  315,  315,  316,  315,  315,
      317,  318,  318,  308,  319,  318,  320,  320,  308,  321,
      320,   31,   31,  322,  323,  324,  320,  320,  325,  326,
      326,  308,  327,  326,  308,  308,  314,  314,  314,  308,
      315,  308,  328,   17,  316,   17,   20,  317,  316,  314,
      329,  330,  315,  315,  315,  315,  315,  315,  315,   58,
      318,  318,  308,  318,  318,  308,  319,  319,  319,  308,
      319,  318,  308,  320,  323,  308,  331,   28,  308,  321,
       31,   31,   31,  322,  323,  324,   37,  320,  325,  321,

      332,  308,  333,  323,  308,   31,  334,  322,  335,  336,
      323,  324,  337,  338,  320,  320,  320,  320,  320,  320,
      320,  320,   99,  326,  326,  308,  326,  308,  327,  326,
      327,  327,  308,  326,  328,  328,  308,  329,  329,  308,
      308,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      319,  308,  331,  331,  308,  332,  333,  333,  308,  104,
       31,  334,  339,  340,  335,  308,  335,  336,  336,  308,
      337,  308,  337,  338,  338,  308,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  326,  328,  329,  308,
      315,  315,  315,  315,  315,  315,  315,  315,  308,  308,

      331,  332,  333,  104,  104,  308,  339,  308,  339,  340,
      340,  308,  335,  336,  337,  338,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  323,  308,  326,  308,  308,
      315,  315,  315,  315,  315,  315,  315,  315,  323,  339,
      340,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      308,  315,  315,  315,  315,  315,  315,  315,  315,  323,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  308,
      315,  341,  315,  315,  323,  320,  323,  320,  320,  320,
      308,  315,  341,  341,  342,  315,  323,  320,  320,  320,
      308,  341,  308,  341,  342,  342,  308,  323,  323,  341,

      342,  323,  323,  341,  323,  308,  341,    0,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308
    } ;

static const flex_int16_t yy_nxt[1116] =
    {   0,
      308,   13,   14,   15,   17,   14,   18,   19,   19,  141,
       19,   19,  304,   12,  308,   20,  186,   21,   23,   24,
       25,   41,   42,   43,  161,   44,   45,   46,   47,   49,
       50,  107,   26,   28,   29,   30,   31,   32,   52,   31,
       33,   34,   35,   36,   37,   38,   39,   53,   54,   46,
       55,   56,   56,  106,   56,   56,  150,  308,  107,   57,
      106,   58,   60,   50,  111,   86,   72,   73,   85,   86,
      308,   61,   62,   79,   80,   56,   56,   87,   56,   56,
       74,   53,   52,   75,   76,   77,  308,   81,   82,   83,
       52,   53,  101,  102,  308,  109,   86,   74,   63,   53,

       64,  103,   74,   65,  110,  125,  126,   66,  132,  133,
       67,  308,  113,   86,   68,   69,   51,   52,  308,   51,
       51,  114,   45,   46,   47,   51,   53,   51,   49,   50,
       51,   51,   51,   88,   89,   90,   91,   92,  308,   91,
       93,   94,   95,   96,   97,   98,   99,  104,  105,  308,
       91,   91,  308,   91,   91,  308,   87,   85,   86,   52,
       85,   86,  308,  127,  128,  129,   87,  130,   53,   87,
      125,  126,   62,  115,  134,  116,   49,   50,  117,   49,
       50,   53,  118,  136,  137,  119,  122,   60,   50,  120,
      121,   84,   85,   86,   84,   84,   61,  139,  140,  308,

       84,   87,   84,   60,   50,   84,   84,   84,   62,  308,
       51,  308,   61,  154,  155,   60,   50,   53,   52,   51,
       52,   51,   51,   52,   61,   51,   51,   53,  308,   53,
       52,   51,   53,   51,   52,  308,   51,   51,   51,   53,
       52,   52,  308,   53,  142,   52,  143,  144,  308,   53,
       53,   72,   73,  308,   53,  308,  145,   72,   73,  147,
      148,  146,   82,   83,  149,   74,   75,   76,   77,   79,
       80,   74,   79,   80,   79,   80,   74,  151,  152,  308,
       74,   82,   83,   81,   85,   86,   81,  308,   81,   85,
       86,   81,  308,   87,  308,   74,  101,  102,   87,  109,

       86,  111,   86,  113,   86,  103,   85,   86,  110,  101,
      102,  308,  114,  101,  102,   87,  158,  159,  103,  163,
       86,  308,  103,  169,  170,  111,   86,  308,  164,  165,
      166,  308,  122,   84,   85,   86,   84,   84,  110,  175,
      176,  308,   84,   87,   84,  125,  126,   84,   84,   84,
      104,  105,  308,  160,  160,  308,  160,  160,  308,   87,
      165,  166,  171,  172,  171,  172,   85,   86,  308,  110,
      308,  114,  308,  114,  308,   87,   52,   85,   86,   85,
       86,   85,   86,  125,  126,   53,   87,  308,   87,  308,
       87,  308,  177,  178,  308,   85,   86,  308,   85,   86,

       85,   86,  191,  180,   87,  308,  179,   87,  181,   87,
      308,   85,   86,  308,  182,  132,  133,  183,  308,  184,
       87,  127,  128,  129,  308,  130,  125,  126,  132,  133,
      134,  132,  133,  125,  126,  188,  137,  187,  136,  137,
      185,  189,  140,  139,  140,  190,   52,   52,  141,  141,
       52,  141,  141,   52,   52,   53,   53,   52,  204,   53,
      201,  155,   53,   53,  154,  155,   53,   95,  192,   52,
      308,  194,  308,  197,  196,  308,  195,  193,   53,  199,
      200,  151,  152,  202,  102,  198,  203,  159,   53,  158,
      159,  205,  206,  207,  208,   81,  207,  208,  211,  212,

      165,  166,  164,  213,  166,  164,  214,  170,  308,  110,
      169,  170,  171,  172,  215,  172,  216,  176,  175,  176,
      308,  114,   85,   86,   85,   86,   85,   86,  308,   85,
       86,   87,  308,   87,  308,   87,   85,   86,   87,  308,
       85,   86,   85,   86,  308,   87,  218,  220,  217,   87,
      308,   87,  228,  229,   85,   86,  219,  222,   85,   86,
      308,  223,  221,   87,  226,  227,  308,   87,  188,  137,
      224,  189,  140,   87,   52,  190,   52,  225,  230,  230,
       52,  230,  230,   53,   52,   53,   52,   52,   52,   53,
       52,  201,  155,   53,   52,   53,   53,   53,  272,   53,

      232,  202,  102,   53,  231,  203,  159,   53,  233,  308,
      234,  237,  199,  200,  236,  235,  205,  206,  238,  240,
      208,   53,  204,  207,  208,  239,  239,  253,  239,  239,
      308,   95,  164,  241,  212,  211,  212,  213,  166,  214,
      170,  215,  172,  216,  176,   85,   86,   85,   86,   85,
       86,  308,   85,   86,   87,  308,   87,  308,   87,   85,
       86,   87,  308,   85,   86,  228,  229,   52,   87,  240,
      208,  243,   87,   85,   86,  242,   53,  244,  245,  308,
       85,   86,   87,   85,   86,  226,  227,  273,  246,   87,
      247,   52,   87,  308,   87,  251,  248,   52,  230,  230,

       53,  230,  230,   52,   52,   52,   53,  252,  249,   52,
       52,  250,   53,   53,   53,  241,  212,  308,   53,   53,
      308,  254,  308,   85,   86,  255,  256,  308,   85,   86,
      308,  257,   87,  258,  259,  260,  105,   87,  239,  239,
      308,  239,  239,  308,  261,   85,   86,  308,   85,   86,
       85,   86,   85,   86,   87,  308,  262,   87,  308,   87,
      308,   87,  308,   85,   86,   85,   86,   85,   86,  263,
      264,  265,   87,   52,   87,  308,   87,  251,  308,  266,
      270,  270,   53,  270,  270,   52,   52,  267,  308,  268,
       52,   52,   52,  308,   53,   53,  308,  271,  269,   53,

       53,   53,  277,  105,   85,   86,   85,   86,   85,   86,
      274,   87,   52,   87,  308,   87,  308,   87,  253,  253,
      308,   53,   85,   86,  253,  253,  260,  105,  276,  275,
      275,   87,  275,  275,   85,   86,  282,  262,  308,  262,
       85,   86,  278,   87,   85,   86,   85,   86,  308,   87,
      284,  292,  293,   87,  308,   87,  308,  281,  279,  285,
      270,  270,  280,  270,  270,   52,   52,   85,   86,  277,
      105,   85,   86,  262,   53,   53,   87,  262,   87,  308,
       87,   85,   86,  308,   85,   86,  286,   52,  294,  293,
       87,  288,  289,   87,  296,  297,   53,  285,  308,  253,

      287,  105,   52,  275,  275,  308,  275,  275,  290,  281,
      308,   53,  291,  291,  262,  291,  291,   85,   86,  308,
      253,  299,   86,  292,  293,  308,   87,  308,   85,   86,
       87,  253,  287,  105,  308,  298,  298,   87,  298,  298,
      300,  301,  297,  291,  291,  308,  291,  291,  296,  297,
      262,  294,  293,  301,  297,  302,  105,  262,  307,  293,
      285,  302,  105,  308,  298,  298,  308,  298,  298,  299,
       86,  305,  306,  305,  306,  303,  303,  308,   87,  303,
      303,  307,  293,   12,   12,   12,   16,   16,   16,   22,
       22,   22,   27,   27,   27,   40,   40,   40,   48,   48,

       48,   51,   51,   59,   59,   59,   70,   70,   71,   71,
       71,   78,   78,   78,   84,   84,   84,  100,  100,  100,
      108,  108,  108,   95,   95,   95,  112,  112,  112,  123,
      123,  123,  124,  124,  124,  131,  131,  131,  135,  135,
      135,  138,  138,  138,  153,  153,  153,  156,  156,  156,
      157,  157,  157,  162,  162,  162,  167,  167,  167,  168,
      168,  168,  173,  173,  173,  174,  174,  174,  209,  209,
      209,  210,  210,  210,  283,  283,  295,  295,  295,   11,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308
    } ;

static const flex_int16_t yy_chk[1116] =
    {   0,
        0,    2,    2,    2,    4,    4,    4,    4,    4,  330,
        4,    4,  300,    4,    0,    4,  123,    4,    6,    6,
        6,   10,   10,   10,  106,   10,   13,   13,   13,   15,
       15,   93,    6,    8,    8,    8,    8,    8,   16,    8,
        8,    8,    8,    8,    8,    8,    8,   16,   17,   17,
       17,   17,   17,   92,   17,   17,   70,   17,   33,   17,
       32,   17,   18,   18,   35,   35,   22,   22,   27,   27,
       11,   18,   19,   25,   25,   19,   19,   27,   19,   19,
       22,   19,   20,   23,   23,   23,    0,   25,   26,   26,
       51,   20,   30,   30,    0,   34,   34,   23,   20,   51,

       20,   30,   26,   20,   34,   40,   40,   20,   43,   43,
       20,    0,   36,   36,   20,   20,   21,   21,    0,   21,
       21,   36,   45,   45,   45,   21,   21,   21,   47,   47,
       21,   21,   21,   28,   28,   28,   28,   28,    0,   28,
       28,   28,   28,   28,   28,   28,   28,   31,   31,    0,
       31,   31,    0,   31,   31,    0,   31,   37,   37,   52,
       38,   38,    0,   41,   41,   41,   37,   41,   52,   38,
       44,   44,   62,   37,   44,   37,   48,   48,   37,   49,
       49,   62,   37,   53,   53,   37,   38,   55,   55,   37,
       37,   39,   39,   39,   39,   39,   55,   61,   61,    0,

       39,   39,   39,   59,   59,   39,   39,   39,   56,   56,
       56,    0,   59,   87,   87,   60,   60,   56,   63,   56,
       65,   56,   58,   58,   60,   58,   58,   63,    0,   65,
       64,   58,   58,   58,   66,    0,   58,   58,   58,   64,
       67,   68,    0,   66,   63,   69,   64,   65,    0,   67,
       68,   71,   71,    0,   69,    0,   66,   72,   72,   67,
       68,   66,   74,   74,   69,   71,   75,   75,   75,   77,
       77,   72,   78,   78,   79,   79,   74,   81,   81,    0,
       75,   82,   82,   77,   84,   84,   78,    0,   79,   85,
       85,   81,    0,   84,    0,   82,   90,   90,   85,   94,

       94,   95,   95,   96,   96,   90,   98,   98,   94,  100,
      100,    0,   96,  101,  101,   98,  103,  103,  100,  107,
      107,    0,  101,  110,  110,  111,  111,    0,  107,  108,
      108,    0,   98,   99,   99,   99,   99,   99,  108,  114,
      114,    0,   99,   99,   99,  124,  124,   99,   99,   99,
      104,  104,    0,  104,  104,    0,  104,  104,    0,  104,
      109,  109,  112,  112,  113,  113,  115,  115,    0,  109,
        0,  112,    0,  113,    0,  115,  142,  116,  116,  117,
      117,  118,  118,  125,  125,  142,  116,    0,  117,    0,
      118,    0,  115,  116,    0,  119,  119,    0,  120,  120,

      121,  121,  142,  118,  119,    0,  117,  120,  118,  121,
        0,  122,  122,    0,  119,  129,  129,  120,    0,  121,
      122,  127,  127,  127,    0,  127,  130,  130,  131,  131,
      130,  132,  132,  134,  134,  135,  135,  134,  136,  136,
      122,  138,  138,  139,  139,  141,  143,  144,  141,  141,
      146,  141,  141,  145,  148,  143,  144,  147,  160,  146,
      153,  153,  145,  148,  154,  154,  147,  160,  143,  149,
        0,  145,    0,  148,  147,    0,  146,  144,  149,  150,
      150,  151,  151,  156,  156,  149,  157,  157,  150,  158,
      158,  161,  161,  162,  162,  151,  163,  163,  164,  164,

      165,  165,  162,  167,  167,  163,  168,  168,    0,  165,
      169,  169,  171,  171,  173,  173,  174,  174,  175,  175,
        0,  171,  177,  177,  178,  178,  179,  179,    0,  180,
      180,  177,    0,  178,    0,  179,  181,  181,  180,    0,
      182,  182,  183,  183,    0,  181,  178,  180,  177,  182,
        0,  183,  187,  187,  184,  184,  179,  182,  185,  185,
        0,  183,  181,  184,  186,  186,    0,  185,  188,  188,
      184,  189,  189,  186,  191,  190,  192,  185,  190,  190,
      193,  190,  190,  191,  194,  192,  195,  196,  197,  193,
      198,  201,  201,  194,  232,  195,  196,  197,  253,  198,

      192,  202,  202,  232,  191,  203,  203,  253,  193,    0,
      194,  197,  199,  199,  196,  195,  205,  205,  198,  209,
      209,  199,  204,  207,  207,  204,  204,  232,  204,  204,
        0,  204,  207,  210,  210,  211,  211,  213,  213,  214,
      214,  215,  215,  216,  216,  217,  217,  218,  218,  219,
      219,    0,  220,  220,  217,    0,  218,    0,  219,  221,
      221,  220,    0,  222,  222,  228,  228,  255,  221,  240,
      240,  218,  222,  223,  223,  217,  255,  219,  220,    0,
      224,  224,  223,  225,  225,  226,  226,  255,  221,  224,
      222,  231,  225,    0,  226,  230,  223,  233,  230,  230,

      231,  230,  230,  234,  236,  235,  233,  231,  224,  237,
      238,  225,  234,  236,  235,  241,  241,    0,  237,  238,
        0,  233,    0,  243,  243,  234,  235,    0,  242,  242,
        0,  236,  243,  237,  238,  239,  239,  242,  239,  239,
        0,  239,  239,    0,  242,  244,  244,    0,  245,  245,
      246,  246,  247,  247,  244,    0,  243,  245,    0,  246,
        0,  247,    0,  248,  248,  249,  249,  250,  250,  244,
      245,  246,  248,  252,  249,    0,  250,  251,    0,  247,
      251,  251,  252,  251,  251,  254,  256,  248,    0,  249,
      257,  258,  259,    0,  254,  256,    0,  252,  250,  257,

      258,  259,  262,  262,  261,  261,  263,  263,  266,  266,
      256,  262,  271,  261,    0,  263,    0,  266,  254,  257,
        0,  271,  264,  264,  258,  259,  260,  260,  261,  260,
      260,  264,  260,  260,  265,  265,  271,  266,    0,  263,
      267,  267,  264,  265,  268,  268,  269,  269,    0,  267,
      272,  283,  283,  268,    0,  269,    0,  270,  265,  272,
      270,  270,  269,  270,  270,  273,  274,  276,  276,  277,
      277,  278,  278,  267,  273,  274,  276,  268,  277,    0,
      278,  279,  279,    0,  280,  280,  273,  282,  284,  284,
      279,  276,  278,  280,  285,  285,  282,  284,    0,  274,

      275,  275,  286,  275,  275,    0,  275,  275,  280,  281,
        0,  286,  281,  281,  279,  281,  281,  288,  288,    0,
      282,  290,  290,  292,  292,    0,  288,    0,  289,  289,
      290,  286,  287,  287,    0,  287,  287,  289,  287,  287,
      291,  295,  295,  291,  291,    0,  291,  291,  296,  296,
      288,  294,  294,  301,  301,  302,  302,  289,  304,  304,
      294,  298,  298,    0,  298,  298,    0,  298,  298,  299,
      299,  305,  305,  303,  303,  299,  299,    0,  299,  303,
      303,  307,  307,  309,  309,  309,  310,  310,  310,  311,
      311,  311,  312,  312,  312,  313,  313,  313,  314,  314,

      314,  315,  315,  316,  316,  316,  317,  317,  318,  318,
      318,  319,  319,  319,  320,  320,  320,  321,  321,  321,
      322,  322,  322,  323,  323,  323,  324,  324,  324,  325,
      325,  325,  326,  326,  326,  327,  327,  327,  328,  328,
      328,  329,  329,  329,  331,  331,  331,  332,  332,  332,
      333,  333,  333,  334,  334,  334,  335,  335,  335,  336,
      336,  336,  337,  337,  337,  338,  338,  338,  339,  339,
      339,  340,  340,  340,  341,  341,  342,  342,  342,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[21] =
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/tab.l"
#line 2 "src/tab.l"
#include "launchtab.h"

static struct tab *curr_tab;
#line 825 "src/tab.yy.c"

#line 827 "src/tab.yy.c"

#define INITIAL 0
#define INISC 1
#define COMSC 2
#define OPTSC 3
#define VERSC 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "src/tab.l"


#line 1054 "src/tab.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1080 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 36 "src/tab.l"
{handle_comment(curr_tab);                    }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 37 "src/tab.l"
{handle_cronRule(curr_tab);                   }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 38 "src/tab.l"
{handle_globEnvar(curr_tab);                  }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 39 "src/tab.l"
{handle_id(curr_tab);             BEGIN COMSC;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 40 "src/tab.l"
{handle_id(curr_tab);             BEGIN COMSC;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 41 "src/tab.l"
{handle_emptyLine(curr_tab);                  }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 42 "src/tab.l"
{handle_commandMulti(curr_tab);               }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 43 "src/tab.l"
{handle_command(curr_tab);        BEGIN OPTSC;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 45 "src/tab.l"
{handle_verbatimStart(curr_tab);  BEGIN VERSC;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 46 "src/tab.l"
{handle_interval(curr_tab);                   }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 47 "src/tab.l"
{handle_calendar(curr_tab);                   }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 48 "src/tab.l"
{handle_envar(curr_tab);                      }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 49 "src/tab.l"
{handle_stdin(curr_tab);                      }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 50 "src/tab.l"
{handle_stdout(curr_tab);                     }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 51 "src/tab.l"
{handle_stderr(curr_tab);                     }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 53 "src/tab.l"
{handle_verbatimEnd(curr_tab);    BEGIN OPTSC;}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 54 "src/tab.l"
{handle_verbatimLine(curr_tab);               }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 55 "src/tab.l"
{handle_unknownOpt(curr_tab);                 }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 57 "src/tab.l"
{handle_invalid(curr_tab);      yyterminate();}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "src/tab.l"
ECHO;
	YY_BREAK
#line 1241 "src/tab.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INISC):
case YY_STATE_EOF(COMSC):
case YY_STATE_EOF(OPTSC):
case YY_STATE_EOF(VERSC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 308);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 59 "src/tab.l"


int yywrap(void)
{
	return 1;
}

void lex_tab(FILE *f, struct tab *t)
{
	yyin = f;
	yylineno = 1;
	curr_tab = t;
	BEGIN INISC;
	yylex();
}

